{% include 'system/header.phtml' %}
{% include 'system/left-panel.phtml' %}

{% include 'system/header-menu.phtml' %}

<style type="text/css">
    
    @page {
        size: 7in 9.25in;   /* auto is the initial value */
        margin: 0;  /* this affects the margin in the printer settings */
    }
    
    table { 
        page-break-inside:auto;
        border: 1px solid #dee2e6;
        background-color: transparent; 
        border-collapse: collapse; 
        table-layout:fixed; 
        table-layout: fixed;
        width: 100%;
        white-space: nowrap;
    }
    
    tr { 
        page-break-inside:avoid; 
        page-break-after:auto;
    }
    
    td { 
        white-space: nowrap; 
        overflow: hidden; 
        text-overflow: ellipsis; 
        border: 1px solid #dee2e6;
        padding: 5px; 
        word-wrap: break-word;  
        white-space: normal;   
        vertical-align: top;
        font-size: 12pt;     
     }
     
    .row-process{
        width: 250px;
        text-align: left;
     }
     
    .row-staff{
        width: 140px;
        text-align: center;
     }
     
     h6{
         width: 140px;
         white-space: break-word; 
         overflow-wrap: break-word; 
         word-wrap: break-word;
         font-size: 12pt;
     }
</style>

<div class="animated fadeIn" id="matrixContainer">
    <div class="row">
        <div class="col-md-12 overflow-auto" >
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Matriz de versatilidade</strong>
                </div>
            <div class="card-body">
            {% if page.message.message %}
                <div class="alert alert-{{page.message.type}}" role="alert">
                    {{page.message.message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            	<form method="post" autocomplete="off" action="/matrix/show">
            	<input type="hidden" name="submited" value="1">
  				<div class="card">
                  <div class="card-header">
                    <strong>Filtro</strong>
                  </div>
                  <div class="card-body card-block">
                     <div class="row form-group">
                		<div class="input-group">
                        <select name="department" id="department" class="form-control">
                                <option value="0">Selecione uma das opções.</option>
                                {% for department in page.department  %}
                                	<option value="{{department.id}}">{{department.name}}</option>
                                {% endfor %}
                           </select>
                        <div class="input-group-btn"><button class="btn btn-primary"><i class="fa fa-search"></i> Filtrar</button></div>
                      </div>
                      <div class="input-group">
                         {% if page.print %}
                            <button type="submit" style="margin: 5px;" class="btn btn-info btn-sm float-right" data-toggle="modal" formtarget="_blank" formaction="{{ constant('SYS_URL') }}matrix/print">
                              <i class="fa fa-print"></i> Versão para impressão
                            </button>
                        {% endif %}
                      </div>
              		</div>        	
                </div>   
                </form>
            </div>
            
          	<div style="overflow: auto; white-space: nowrap;">     		
               <table id="dataTable">
                    <thead>
                            {% for key,line in page.return %}
                            	<tr>
                                {% if key == 0 %}                                                 
                                    	{% for column in line %}
                                    		{% if column.photo == 1 %}
                                        		<td class="row-process">
                                        			<h6 class="text-center">{{column.name}}</h6><br>
                                        			<div><image src="{{ constant('SYS_URL') }}images/skill-icons/0.png" style="width: 25px;" /> Não habilitado</div>
                                        			<div><image src="{{ constant('SYS_URL') }}images/skill-icons/1.png" style="width: 25px;" /> Treinamento programado</div>
                                        			<div><image src="{{ constant('SYS_URL') }}images/skill-icons/2.png" style="width: 25px;" /> Em treinamento</div>
                                        			<div><image src="{{ constant('SYS_URL') }}images/skill-icons/3.png" style="width: 25px;" /> Habilitado / Certificado</div>
                                        			<div><image src="{{ constant('SYS_URL') }}images/skill-icons/4.png" style="width: 25px;" /> Treinador</div>
                                        		</td>
                                        	{% else %}
                                        		<td class="row-staff">
                                        			<img src="{% if column.photo %}
                                                   				{{column.photo}}
                                                   			{%else%}
                                                   				{{ constant('SYS_URL') }}images/photo-icon.svg
                                                   			{% endif %}" style="height:150px; width:auto; max-width: 130px;">
                                        			<h6>{{column.name}}</h6>
                                        			<!-- <p>
                                            			{{column.department}}
                                            			 / {{column.role}}
                                        			</p> -->
                                        		</td>
                                        	{% endif %}
                                    	{% endfor %}
                                
                                {% else %}
                                     
                                    	{% for key, column in line %}
                                    		{% if key == 0 %} 
                                        		<td>
                                            		<a href="#" style="color:#000000;" data-toggle="tooltip" data-html="true" data-placement="right" {% if column.description %} title="{{column.description}}" {% endif %}>{{column.name}}</a>
                                            		 
                                            	</td>
                                            {% else %}
                                            	<td class="text-center">
                                            		<a href="#" data-toggle="tooltip" data-placement="right" title="{{column.name}}{% if column.coach %} treinado por {{column.coach}} em {{column.date}} {% endif %}">
                                            			<image src="{{ constant('SYS_URL') }}images/skill-icons/{{column.level}}.png" style="width: 25px;">
                                            		</a>

                                            	</td>
                                            {% endif %}
                                        		
                                    	{% endfor %}

                                {% endif %}  
                                </tr>  	
                            {% endfor %}
                        </tr>
                    </thead>
                </table>
            
            	<br>
           	</div> 
           </div>
        </div>
    </div>
  </div><!-- .animated -->
</div><!-- .content -->
<script>
jQuery(function ($) {

	$('#department').selectpicker();
	
	var matrixWidth = window.screen.width - 280;
	console.log(matrixWidth);
	$("#matrixContainer").width(matrixWidth);

    {% if page.filter.department %}
	$("#department").val("{{page.filter.department}}");	
	{% endif %} 
	
    	$('[data-toggle="tooltip"]').tooltip();
    } );

</script>


{% include 'system/footer.phtml' %}