{% include 'system/header.phtml' %} {% include 'system/left-panel.phtml'
%} {% include 'system/header-menu.phtml' %}

<div class="animated fadeIn">
	<div class="row">

		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<strong class="card-title">Aqui você cadastra ou atualiza dados de um procedimento.</strong>
				</div>
				<div class="card-body">

					{% if page.message %}
					<div class="alert alert-{{page.message.type}}" role="alert">
						{{page.message.message}}
						<button type="button" class="close" data-dismiss="alert"
							aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					{% endif %}

					<form method="post" autocomplete="off" action="/process/save" id="easyForm"
						data-toggle="validator" role="form">
						<input type="hidden" name="id" value="{{page.dataset.id}}">
						<input type="hidden" name="company" value="{{user.company}}">
						<div class="card">
							<div class="card-header">
								<strong>Procedimento</strong>
							</div>
							<div class="card-body card-block">
								<div class="row form-group">
									<div class="col">
										<label for="name" class="form-control-label">Nome:</label> <input
											type="text" name="name" id="name" placeholder="Nome do procedimento"
											class="form-control" value="{{page.dataset.name}}" required>
									</div>
								</div>
								<div class="row form-group">
									<div class="col">
										<label for="description" class="form-control-label">Descrição:</label>
										<textarea data-autoresize name="description" id="description" placeholder="Descreva o procedimento"
											class="form-control">{{page.dataset.description}}</textarea>
									</div>
								</div>
								<div class="row form-group">
                               		<div class="col">
                               			<label for="role">Departamento:</label>
                               			<button type="button" class="btn btn-success btn-sm float-right" onclick="location.href ='{{ constant('SYS_URL') }}department/form'">
                                          <i class="fa fa-plus-circle"></i>
                                        </button>
                              			<select name="department" id="department" class="form-control">
                                            <option value="0">Selecione uma das opções.</option>
                                            {% for department in page.department  %}
                                            	<option value="{{department.id}}">{{department.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                          		</div>  
								<div class="card-footer text-right">
									<button type="submit" class="btn btn-primary btn-sm">
										<i class="fa fa-dot-circle-o"></i> Salvar
									</button>
								</div>
							</div>
					
					</form>
				</div>

			</div>
		</div>
	</div>
</div>
</div>
<!-- .animated -->
</div>
<!-- .content -->



<script src="{{ constant('SYS_URL') }}assets/js/validator.js"></script>
<script src="{{ constant('SYS_URL') }}assets/js/easyform.js"></script>

<script>
jQuery(function ($) { 

	jQuery.each(jQuery('textarea[data-autoresize]'), function() {
	    var offset = this.offsetHeight - this.clientHeight;
	 
	    var resizeTextarea = function(el) {
	        jQuery(el).css('height', 'auto').css('height', el.scrollHeight + offset);
	    };
	    jQuery(this).on('keyup input', function() { resizeTextarea(this); }).removeAttr('data-autoresize');
	});
	
    var dataSet = {{page.dataset|json_encode()|raw}};

    {% if page.dataset.department %}
	$("#department").val("{{page.dataset.department}}");	
	{% endif %} 
    
    EasyForm.init(dataSet);
    $('#easyForm').validator();
});
    </script>


{% include 'system/footer.phtml' %}
