-- MySQL Script generated by MySQL Workbench
-- Mon Feb 25 22:14:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pgestao_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pgestao_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pgestao_app` DEFAULT CHARACTER SET utf8 ;
USE `pgestao_app` ;

-- -----------------------------------------------------
-- Table `pgestao_app`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique ID for the company',
  `name` VARCHAR(128) NOT NULL COMMENT 'Company name',
  `trade` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Trading name of the company',
  `number` BIGINT(14) NOT NULL COMMENT 'Corporate Tax Payer Registration',
  `expire` DATE NULL DEFAULT NULL COMMENT 'Expiration date',
  `created` DATETIME NOT NULL COMMENT 'Date of registration on the system',
  `deleted` DATETIME NULL DEFAULT NULL,
  `changed` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `company` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_company1_idx` (`company` ASC),
  CONSTRAINT `fk_department_company1`
    FOREIGN KEY (`company`)
    REFERENCES `pgestao_app`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`menu` (
  `id` INT(11) NOT NULL COMMENT 'Unique identity number',
  `name` VARCHAR(128) NOT NULL,
  `label` VARCHAR(45) NOT NULL COMMENT 'Displayed name ',
  `url` VARCHAR(512) NULL DEFAULT '#' COMMENT 'Full electronic address',
  `title` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Title of the link',
  `icon` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Display icon of the Font Awesome Library',
  `parent` INT(11) NULL DEFAULT '0' COMMENT 'Parent on the tree',
  `allow` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Roles that has access to the menu, separated by ;',
  `display` TINYINT(4) NULL DEFAULT '0' COMMENT 'Show on the menu',
  `order` INT(11) NULL DEFAULT NULL COMMENT 'Sequence in the menu',
  `commentary` VARCHAR(512) NULL DEFAULT NULL COMMENT 'Comment about the page',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  `department` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_department1_idx` (`department` ASC),
  CONSTRAINT `fk_role_department1`
    FOREIGN KEY (`department`)
    REFERENCES `pgestao_app`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'Name of employee',
  `gender` CHAR(1) NULL DEFAULT NULL COMMENT 'Gender of employee',
  `photo` BLOB NULL DEFAULT NULL,
  `registration` VARCHAR(15) NULL,
  `shift` VARCHAR(15) NULL,
  `notes` TEXT NULL,
  `status` SMALLINT(1) NULL DEFAULT 1,
  `company` INT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_role1_idx` (`role` ASC),
  CONSTRAINT `fk_staff_role1`
    FOREIGN KEY (`role`)
    REFERENCES `pgestao_app`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `photo` LONGBLOB NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0=disabled\n1=okay\n2=need validation\n3=expired',
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `company` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  `changed` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC),
  INDEX `fk_user_company1_idx` (`company` ASC),
  CONSTRAINT `fk_user_company1`
    FOREIGN KEY (`company`)
    REFERENCES `pgestao_app`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `description` VARCHAR(512) NULL,
  `company` INT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_process_department1_idx` (`department` ASC),
  CONSTRAINT `fk_process_department1`
    FOREIGN KEY (`department`)
    REFERENCES `pgestao_app`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pgestao_app`.`staff_know_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`staff_know_process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `level` SMALLINT(2) NULL DEFAULT 0,
  `coach` VARCHAR(124) NULL,
  `commentary` TEXT NULL,
  `inserted_by_manager` TINYINT NULL,
  `process` INT NOT NULL,
  `staff` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_know_process_process1_idx` (`process` ASC),
  INDEX `fk_staff_know_process_staff1_idx` (`staff` ASC),
  CONSTRAINT `fk_staff_know_process_process1`
    FOREIGN KEY (`process`)
    REFERENCES `pgestao_app`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_know_process_staff1`
    FOREIGN KEY (`staff`)
    REFERENCES `pgestao_app`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pgestao_app`.`role_has_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`role_has_process` (
  `role` INT NOT NULL,
  `process` INT NOT NULL,
  INDEX `fk_role_has_process_role1_idx` (`role` ASC),
  INDEX `fk_role_has_process_process1_idx` (`process` ASC),
  CONSTRAINT `fk_role_has_process_role1`
    FOREIGN KEY (`role`)
    REFERENCES `pgestao_app`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_process_process1`
    FOREIGN KEY (`process`)
    REFERENCES `pgestao_app`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pgestao_app`;

DELIMITER $$
USE `pgestao_app`$$
CREATE DEFINER = CURRENT_USER TRIGGER `pgestao_app`.`company_BEFORE_INSERT` BEFORE INSERT ON `company` FOR EACH ROW
BEGIN
	SET NEW.created = now();
END$$

USE `pgestao_app`$$
CREATE DEFINER = CURRENT_USER TRIGGER `pgestao_app`.`user_BEFORE_INSERT` BEFORE INSERT ON `user` FOR EACH ROW
BEGIN
	SET NEW.created = now();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pgestao_app`.`company`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgestao_app`;
INSERT INTO `pgestao_app`.`company` (`id`, `name`, `trade`, `number`, `expire`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'Pró Gestão', 'Pró Gestão', 4484352000110, '2025-01-01', DEFAULT, NULL, NULL);
INSERT INTO `pgestao_app`.`company` (`id`, `name`, `trade`, `number`, `expire`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'Demonstração S.A.', 'Demonstração S.A.', 4484352000110, '2025-01-01', DEFAULT, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgestao_app`.`department`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgestao_app`;
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (1, 'Tecnoclogia da informação e comunica', 'O departamento de tecnologia da informação e comunicação congrega os segmentos Telecom, Hardwares de informática e Software e Serviços de TI. Responsável por sustentar a parte tecnológica da empresa e planejar os investimento em tecnologia. ', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (2, 'Financeiro', 'O departamento financeiro é aquele que administra os recursos de uma empresa. Ele faz o controle da tesouraria, dos investimentos e dos riscos, além da gestão de contas e impostos, do planejamento financeiro da companhia e da divulgação de seus resultados', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (3, 'Administrativo', 'O setor administrativo é o coração da empresa. Ele é responsável pelo planejamento estratégico e pela gestão das tarefas, coordenando e fiscalizando os demais setores e fornecendo os dados necessários para a tomada de decisões pelos executivos da companhi', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (4, 'Recursos humanos', 'O departamento de recursos humanos é o responsável pelo recrutamento do pessoal e pela gestão de pessoas. Ele busca soluções para conflitos, controla os horários de entrada e saída dos trabalhadores, as horas extras e estabelece políticas para a retenção ', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (5, 'Comercial', 'Também chamado de departamento de marketing, o foco do setor comercial é nos clientes externos da empresa. Ele é o responsável pelas vendas, garantindo a geração de receitas para a empresa.', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (6, 'Operacional', 'O departamento operacional, que em alguns casos pode ser chamado de setor de produção ou de setor técnico, é o responsável por administrar todo o processo de transformação dos insumos no produto final.', 1);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (7, 'Tecnoclogia da informação e comunica', 'O departamento de tecnologia da informação e comunicação congrega os segmentos Telecom, Hardwares de informática e Software e Serviços de TI. Responsável por sustentar a parte tecnológica da empresa e planejar os investimento em tecnologia. ', 2);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (8, 'Financeiro', 'O departamento financeiro é aquele que administra os recursos de uma empresa. Ele faz o controle da tesouraria, dos investimentos e dos riscos, além da gestão de contas e impostos, do planejamento financeiro da companhia e da divulgação de seus resultados', 2);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (9, 'Administrativo', 'O setor administrativo é o coração da empresa. Ele é responsável pelo planejamento estratégico e pela gestão das tarefas, coordenando e fiscalizando os demais setores e fornecendo os dados necessários para a tomada de decisões pelos executivos da companhi', 2);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (10, 'Recursos humanos', 'O departamento de recursos humanos é o responsável pelo recrutamento do pessoal e pela gestão de pessoas. Ele busca soluções para conflitos, controla os horários de entrada e saída dos trabalhadores, as horas extras e estabelece políticas para a retenção ', 2);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (11, 'Comercial', 'Também chamado de departamento de marketing, o foco do setor comercial é nos clientes externos da empresa. Ele é o responsável pelas vendas, garantindo a geração de receitas para a empresa.', 2);
INSERT INTO `pgestao_app`.`department` (`id`, `name`, `description`, `company`) VALUES (12, 'Operacional', 'O departamento operacional, que em alguns casos pode ser chamado de setor de produção ou de setor técnico, é o responsável por administrar todo o processo de transformação dos insumos no produto final.', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgestao_app`.`menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgestao_app`;
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (1, 'menuCadastros', 'Cadastros', NULL, NULL, NULL, NULL, ';user;manager;admin;', 1, 1000, 'Grupo de cadastros do sistema');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (2, 'menuRelatorios', 'Relatórios', NULL, NULL, NULL, NULL, ';user;manager;admin;', 1, 2000, 'Grupo de cadastros do sistema');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (3, 'menuConfiguracao', 'Configurações', NULL, NULL, NULL, NULL, ';manager;admin;', 1, 9000, 'Grupo de cadastros do sistema');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (4, 'home', 'Página inicial', NULL, NULL, NULL, NULL, ';guess;user;manager;admin;', NULL, NULL, 'Página inicial do sistema');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (5, 'login', 'Login', NULL, NULL, NULL, NULL, ';guess;user;manager;admin;', NULL, NULL, 'Ação de login');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (6, 'logout', 'Logout', NULL, NULL, NULL, NULL, ';guess;user;manager;admin;', NULL, NULL, 'Ação de logout');
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (7, 'data.import', 'Importador', '/data/import', 'Importadores de dados', 'ti-cloud-up', 3, ';manager;admin;', 1, 9300, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (8, 'company.list', 'Empresas', '/company', 'Lista de empresas', 'fa-building-o', 3, ';admin;', 1, 9100, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (9, 'company.form', 'Cadastro de empresa', '/company/form', 'Formulário de cadastro de empresa', NULL, NULL, ';admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (10, 'company.save', 'Salvar empresas', '/company/save', 'Ação para salvar empresas', NULL, NULL, ';admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (11, 'company.update', 'Atualização de empresas', '/company/form/[{id}]', 'Formulário de atualização de empresas', NULL, NULL, ';admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (12, 'users.list', 'Usuáros', '/user', 'Lista de usuários', 'fa-unlock-alt', 3, ';manager;admin;', 1, 9200, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (13, 'users.form', 'Cadastro de usuários', '/users/form', 'Formulário de cadastro de usuários', NULL, NULL, ';manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (14, 'users.save', 'Salvar usuário', '/user/save', 'Ação para salvar usuário', NULL, NULL, ';manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (15, 'users.update', 'Atualizar usuário', '/user/form/[{uid}]', 'Formulário de atualização de usuários', NULL, NULL, ';manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (16, 'users.profile', 'Perfil de usuário', '/profile/{id}', 'Formuário de perfil de usuário', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (17, 'department.list', 'Departamentos', '/department', 'Lista de departamentos', 'fa-sitemap', 1, ';user;manager;admin;\'', 1, 1100, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (18, 'department.form', 'Cadastro de departamento', '/department/form', 'Formulário de cadastro de departamento', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (19, 'department.save', 'Salvar departamento', '/department/save', 'Ação para salvar departamento', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (20, 'department.update', 'Atualizar departamento', '/department/form/[{id}]', 'Formulário de atualização de departamento', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (21, 'role.list', 'Cargos', '/role', 'Lista de cargos', 'ti-id-badge', 1, ';user;manager;admin;\'', 1, 1200, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (22, 'role.form', 'Cadastro de cargo', '/role/form', 'Formulário de cadastro de cargo', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (23, 'role.save', 'Salvar cargo', '/role/save', 'Ação para salvar cargo', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (24, 'role.update', 'Atualizar cargo', '/role/form/[{id}]', 'Formulário de atualização de cargo', NULL, NULL, ';user;manager;admin;\'', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (25, 'role.bydepartment', 'Lista de cargos de um departamento', '/role/by/department/[{department}]', 'Webservice que retorna uma lista de cargos por departamento', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (26, 'process.list', 'Procedimentos', '/process', 'Lista de procedimentos', 'fa-check-square-o', 1, ';user;manager;admin;', 1, 1300, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (27, 'process.form', 'Cadastro de procedimento', '/process/form', 'Formulário de cadastro de procedimento', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (28, 'process.save', 'Salvar procedimento', '/process/save', 'Ação para salvar procedimento', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (29, 'process.update', 'Atualizar procedimento', '/process/form/[{id}]', 'Formulário de atualização de procedimento', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (30, 'staff.list', 'Colaboradores', '/staff', 'Lista de colaboradores', 'fa-users', 1, ';user;manager;admin;', 1, 1500, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (31, 'staff.form', 'Cadastro de colaborador', '/staff/form', 'Forulário de cadastro de colaboradores', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (32, 'staff.save', 'Salvar colaborador', '/staff/save', 'Ação para salvar colaboradores', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (33, 'staff.update', 'Atualizar colaborador', '/staff/form/[{id}]', 'Formulário de atualização de colaboradores', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (34, 'staff.addskill', 'Adicionar habilidade', '/staff/addskill', 'Ação para salvar habilidade do colaborador', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (35, 'staff.delskill', 'Remover habilidade', '/staff/delskill/[{param}]', 'Ação para remover habilidade do colaborador', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (36, 'staff.status', 'Atualizar status', '/staff/status/[{param}]', 'Açào para atualizar o status do colaborador', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (37, 'matrix.list', 'Matriz', '/matrix', 'Matriz de polivalência e versatilidade', 'fa-table', 2, ';user;manager;admin;', 1, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (38, 'matrix.print', 'Matriz para impressão', '/matrix/print', 'Matriz de polivalência e versatilidade para impressão', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);
INSERT INTO `pgestao_app`.`menu` (`id`, `name`, `label`, `url`, `title`, `icon`, `parent`, `allow`, `display`, `order`, `commentary`) VALUES (39, 'matrix.show', 'Matriz', '/matrix/show', 'Matriz de polivalência e versatilidade para impressão', NULL, NULL, ';user;manager;admin;', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgestao_app`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgestao_app`;
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (1, 'Auxiliar de Faturamento', 'Calcula a movimentação diária do faturamento, encaminhando aos setores competentes, conforme normas e procedimentos da empresa ; auxilia nos controles de documentos (pedidos) que dão entrada para sejam feitos os respectivos faturamento; preenche minutas, c', 2);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (2, 'Encarregado de Recursos Humanos', 'Está sob as responsabilidades de um Encarregado de Recursos Humanos manter o plano de cargos, salários e carreira da empresa de acordo com as normas da instituição, prestar informações aos funcionários da instituição sobre procedimentos do setor de recurso', 4);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (3, 'Analista Comercial Interno ', 'Está sob as responsabilidades de um Analista Comercial Interno realizar a atualização de cadastros de clientes, fazer tratamento e arquivamento de documentação, analisar o volume de faturamento, assim como a análise de processos de venda , cotações, propos', 5);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (4, 'Gerente Administrativo', 'Um Gerente Administrativo atua com a gestão da equipe, respondendo pelos recursos humanos, supervisionando o setor de compras dando assessoria a presidência da empresa, elaborando relatórios gerenciais e conduzir reuniões de recursos materiais e financeiro', 3);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (5, 'Coordenador de Infraestrutura', 'Administra as rotinas de manutenção, implantação e configuração de infraestrutura de telecomunicações, redes, servidores e internet, acompanha o suporte aos usuários e desenvolve soluções de tecnologia, a fim de manter a alta disponibilidade dos serviços.', 1);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (6, 'Eletricista de Manutenção ', 'Está sob as responsabilidades de um Eletricista de Manutenção executar manutenção elétrica, preventiva e corretiva, a fim de manter máquinas, equipamentos, motores, painéis, rede elétrica, aparelhos e instalações em perfeitas condições de funcionamento, at', 6);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (7, 'Fresador', 'Está sob as responsabilidades de um Fresador operar máquina de fresa, documentar suas atividades e manter os formulários, como os de produção e de ocorrência de manutenção das máquinas, sempre atualizados, obter diferentes cortes nos materiais, abrir fenda', 6);
INSERT INTO `pgestao_app`.`role` (`id`, `name`, `description`, `department`) VALUES (8, 'Fundidor', 'Está sob as responsabilidades de um Fundidor atuar com fabricação e fundição de medalhas, atuar com vulcanização e fundição, dar acabamento em peças de metais, fundir peças em moldes em conquilhas, fazer a reparação das peças, fazer a verificação e organiz', 6);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgestao_app`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgestao_app`;
INSERT INTO `pgestao_app`.`user` (`uid`, `name`, `email`, `password`, `photo`, `status`, `role`, `company`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'qunY2fg6OlJCNDFKeUZxQlhMdGZGRT0=', 'iunY2fjTiAG6TaY90HxRbGSYuPc6OlJCNDFKeUZxQlhMdGZGRT0=', '3f75509b223bf62b576179ee29493e7fa990d6cd92989277d1dab04d5f25130e', NULL, 1, 'admin', 1, DEFAULT, NULL, NULL);
INSERT INTO `pgestao_app`.`user` (`uid`, `name`, `email`, `password`, `photo`, `status`, `role`, `company`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'ueLRwv/0l0adTKcy2iA6OlJCNDFKeUZxQlhMdGZGRT0=', 'meLRwv/0lya9TKcy2iAcbSoHu2GQOjpSQjQxSnlGcUJYTHRmRkU9', '22cebd283728bad166ea068666c5dbcd96ec9486a9a72b34bd98e2b9f9ba6b8f', NULL, 1, 'admin', 1, DEFAULT, NULL, NULL);
INSERT INTO `pgestao_app`.`user` (`uid`, `name`, `email`, `password`, `photo`, `status`, `role`, `company`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'r+TH0/PmOjpSQjQxSnlGcUJYTHRmRkU9', 'j+TH0/PmuBa4W6Eo3j0cYHzSfGXLOjpSQjQxSnlGcUJYTHRmRkU9', '3f75509b223bf62b576179ee29493e7fa990d6cd92989277d1dab04d5f25130e', NULL, 1, 'admin', 1, DEFAULT, NULL, NULL);
INSERT INTO `pgestao_app`.`user` (`uid`, `name`, `email`, `password`, `photo`, `status`, `role`, `company`, `created`, `deleted`, `changed`) VALUES (DEFAULT, 'r+jY3/jgjBS+/XWfHD06OlJCNDFKeUZxQlhMdGZGRT0=', 'j+jY39bjnwOsSrMzkTFdbg8+nDo6UkI0MUp5RnFCWEx0ZkZFPQ==', '4e09b666a1921760f2f9f5ddad85483095b16340ca65de7c6dbdf87551c5bc1b', NULL, 1, 'manager', 2, DEFAULT, NULL, NULL);

COMMIT;

