-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 20:08:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pgestao_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pgestao_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pgestao_app` DEFAULT CHARACTER SET utf8 ;
USE `pgestao_app` ;

-- -----------------------------------------------------
-- Table `pgestao_app`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique ID for the company',
  `name` VARCHAR(128) NOT NULL COMMENT 'Company name',
  `trade` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Trading name of the company',
  `number` BIGINT(14) NOT NULL COMMENT 'Corporate Tax Payer Registration',
  `expire` DATE NULL DEFAULT NULL COMMENT 'Expiration date',
  `created` DATETIME NOT NULL COMMENT 'Date of registration on the system',
  `deleted` DATETIME NULL DEFAULT NULL,
  `changed` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `company` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_company1_idx` (`company` ASC),
  CONSTRAINT `fk_department_company1`
    FOREIGN KEY (`company`)
    REFERENCES `pgestao_app`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`menu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique identity number',
  `name` VARCHAR(128) NOT NULL,
  `label` VARCHAR(45) NOT NULL COMMENT 'Displayed name ',
  `url` VARCHAR(512) NULL DEFAULT '#' COMMENT 'Full electronic address',
  `title` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Title of the link',
  `icon` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Display icon of the Font Awesome Library',
  `parent` INT(11) NULL DEFAULT '0' COMMENT 'Parent on the tree',
  `allow` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Roles that has access to the menu, separated by ;',
  `display` TINYINT(4) NULL DEFAULT '0' COMMENT 'Show on the menu',
  `order` INT(11) NULL DEFAULT NULL COMMENT 'Sequence in the menu',
  `commentary` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Comment about the page',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  `department` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_department1_idx` (`department` ASC),
  CONSTRAINT `fk_role_department1`
    FOREIGN KEY (`department`)
    REFERENCES `pgestao_app`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`skill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `description` VARCHAR(265) NULL DEFAULT NULL,
  `company` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`staff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'Name of employee',
  `gender` CHAR(1) NULL DEFAULT NULL COMMENT 'Gender of employee',
  `photo` BLOB NULL DEFAULT NULL,
  `registration` VARCHAR(15) NULL,
  `shift` INT NULL,
  `role` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_role1_idx` (`role` ASC),
  CONSTRAINT `fk_employee_role1`
    FOREIGN KEY (`role`)
    REFERENCES `pgestao_app`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`staff_has_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`staff_has_skill` (
  `staff` INT(11) NOT NULL,
  `skill` INT(11) NOT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `coach` VARCHAR(45) NULL COMMENT '	',
  `date` DATE NULL,
  PRIMARY KEY (`staff`, `skill`),
  INDEX `fk_employee_has_skill_skill1_idx` (`skill` ASC),
  INDEX `fk_employee_has_skill_employee1_idx` (`staff` ASC),
  CONSTRAINT `fk_employee_has_skill_employee1`
    FOREIGN KEY (`staff`)
    REFERENCES `pgestao_app`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_skill_skill1`
    FOREIGN KEY (`skill`)
    REFERENCES `pgestao_app`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`user` (
  `uid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `photo` LONGBLOB NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0=disabled\n1=okay\n2=need validation\n3=expired',
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `company` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  `changed` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC),
  INDEX `fk_user_company1_idx` (`company` ASC),
  CONSTRAINT `fk_user_company1`
    FOREIGN KEY (`company`)
    REFERENCES `pgestao_app`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pgestao_app`.`role_has_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgestao_app`.`role_has_skill` (
  `role_id` INT(11) NOT NULL,
  `skill_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `skill_id`),
  INDEX `fk_role_has_skill_skill1_idx` (`skill_id` ASC),
  INDEX `fk_role_has_skill_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_has_skill_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `pgestao_app`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_skill_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `pgestao_app`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
