<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Pró Gestão - Polivalencia, versatilidade, talentos e certificações.</title>
    <meta name="description" content="Sistema de gestão de talentos, habilidades e treinamentos, simplifique sua gestão de recurso humanos através desta excelente ferramenta, a matriz de polivalência lhe ajudará a tomar decisões, controle certificações e habilidades e identifique talentos em sua empresa.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{{ constant('SYS_URL') }}images/favicon.png">
    <link rel="shortcut icon" href="{{ constant('SYS_URL') }}images/favicon.png">

    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/normalize.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/themify-icons.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/bootstrap-select.less">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/scss/style.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/lib/vector-map/jqvmap.min.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/lib/datatable/select.dataTables.min.css">
    <link rel="stylesheet" href="{{ constant('SYS_URL') }}assets/css/lib/croppie/2.6.2/croppie.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <script src="{{ constant('SYS_URL') }}assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/popper.min.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/bootstrap.min.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/plugins.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/main.js"></script>

</head>
<body>

