{% include 'system/header.phtml' %}

	
    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="/">
                        <img class="align-content" src="{{ constant('SYS_URL') }}images/logo.png" alt="Pró Gestão - Versátil" style="width:250px;margin:5px;">
                    </a>
                </div>
            {% if page.message %}
        		<div class="alert alert-{{page.message.type}}" role="alert">
                	{{page.message.message}}
                	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    	<span aria-hidden="true">&times;</span>
                    </button>
                </div>
        	{% endif %}
                <div class="login-form">
                    <form action="{{ constant('SYS_URL') }}login" method="POST">
                        <div class="form-group">
                            <label>E-mail:</label>
                            <input type="email" class="form-control" placeholder="E-mail" name="email">
                        </div>
                        <div class="form-group">
                            <label>Senha:</label>
                            <input type="password" class="form-control" placeholder="Senha" name="password">
                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Entrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script src="{{ constant('SYS_URL') }}assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/popper.min.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/plugins.js"></script>
    <script src="{{ constant('SYS_URL') }}assets/js/main.js"></script>


</body>
</html>
